<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14.0</LangVersion>
        <IsTestProject>true</IsTestProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>InventarWorkerServiceIntegrationTests</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <DocumentationFile>bin/$(Configuration)/$(TargetFramework)/InventarWorkerServiceIntegrationTest.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.0">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Playwright.MSTest" Version="1.59.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
        <PackageReference Include="MSTest.TestAdapter" Version="4.2.1" />
        <PackageReference Include="MSTest.TestFramework" Version="4.2.1" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.Playwright.MSTest" />
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
        <Using Include="System.Text.RegularExpressions" />
        <Using Include="System.Threading.Tasks" />
    </ItemGroup>

</Project>
