using System.Globalization;
using System.Text.Json;
using CsvHelper;
using Dapper;
using InventarWorkerCommon.Models.Hardware;
using InventarWorkerCommon.Models.Software;
using InventarWorkerCommon.Models.SqlDatabase;
using InventarWorkerCommon.Services.Csv;
using Npgsql;

namespace InventarWorkerCommon.Services.Database;

/// <summary>
/// DE: Kapselt den Zugriff auf PostgreSQL fuer Inventar-, Lookup- und Wartungsoperationen.
/// EN: Encapsulates PostgreSQL access for inventory, lookup, and maintenance operations.
/// </summary>
public class PgSqlDbService
{
    private readonly string _connectionString;

    /// <summary>
    /// DE: Initialisiert eine neue Instanz des PostgreSQL-Dienstes.
    /// EN: Initializes a new instance of the PostgreSQL service.
    /// </summary>
    /// <param name="connectionString">
    /// DE: Verbindungszeichenfolge fuer die PostgreSQL-Datenbank.
    /// EN: Connection string for the PostgreSQL database.
    /// </param>
    public PgSqlDbService(string connectionString)
    {
        _connectionString = connectionString;
    }

    /// <summary>
    /// DE: Erstellt die benoetigten Tabellen, Indizes und Views fuer PostgreSQL.
    /// EN: Creates the required PostgreSQL tables, indexes, and views.
    /// </summary>
    public void InitializeDatabase()
    {
#if DEBUG
        var targetDatabase = GetTargetDatabaseName();
        EnsureDatabaseExists(targetDatabase);
#else
        EnsureDatabaseExists(GetTargetDatabaseName());
#endif

        using var connection = new NpgsqlConnection(_connectionString);
        connection.Open();

        var createTablesAndViewsQuery =
            """
            CREATE TABLE IF NOT EXISTS Machines (
                Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                Name TEXT NOT NULL UNIQUE,
                OperatingSystem TEXT,
                LastSeen timestamptz,
                CreatedAt timestamptz DEFAULT now(),
                IPv4 TEXT,
                IPv6 TEXT,
                FQDN TEXT,
                Disabled BOOLEAN NOT NULL DEFAULT FALSE,
                Deprovisioned BOOLEAN NOT NULL DEFAULT FALSE,
                LastHarvested timestamptz
            );

            CREATE TABLE IF NOT EXISTS HardwareInventories (
               Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               MachineId INTEGER NOT NULL,
               ComputerName TEXT,
               ComputerModel TEXT,
               ComputerManufacturer TEXT,
               Architecture TEXT,
               ProcessorName TEXT,
               ProcessorCores INTEGER,
               TotalMemoryGB REAL,
               AvailableMemoryGB REAL,
               MemoryUsagePercent REAL,
               CreatedAt timestamptz DEFAULT now(),
               FOREIGN KEY (MachineId) REFERENCES Machines(Id)
            );

            CREATE TABLE IF NOT EXISTS SoftwareInventories (
               Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               MachineId INTEGER NOT NULL,
               ProcessesJson TEXT,
               InstalledSoftwareJson TEXT,
               ServicesJson TEXT,
               EnvironmentJson TEXT,
               StartupProgramsJson TEXT,
               RuntimeJson TEXT,
               CreatedAt timestamptz DEFAULT now(),
               FOREIGN KEY (MachineId) REFERENCES Machines(Id)
            );

            CREATE INDEX IF NOT EXISTS idx_machines_name ON Machines(Name);
            CREATE INDEX IF NOT EXISTS idx_hardware_machine_created ON HardwareInventories(MachineId, CreatedAt);
            CREATE INDEX IF NOT EXISTS idx_software_machine_created ON SoftwareInventories(MachineId, CreatedAt);

            DROP VIEW IF EXISTS hardware_inventory_view;

            CREATE OR REPLACE VIEW HardwareInventoryView AS
            SELECT DISTINCT ON (m.id)
                m.id AS MachineID,
                m.name AS MachineName,
                h.Architecture,
                h.ProcessorCores,
                ROUND(h.TotalMemoryGB::numeric / 1024 / 1024 / 1024, 2) AS TotalMemoryGB,
                ROUND(h.AvailableMemoryGB::numeric / 1024 / 1024 / 1024, 2) AS AvailableMemoryGB,
                ROUND(h.MemoryUsagePercent::numeric, 2) AS MemoryUsagePercent
            FROM Machines m
                JOIN HardwareInventories h ON h.MachineId = m.Id
            ORDER BY m.Id, h.CreatedAt DESC;

            CREATE OR REPLACE VIEW LatestSoftwareInventoriesView AS
            SELECT si.*
            FROM SoftwareInventories si
                INNER JOIN (
                    SELECT MachineId, MAX(CreatedAt) AS MaxCreatedAt
                    FROM SoftwareInventories
                    GROUP BY MachineId
                ) latest ON si.MachineId = latest.MachineId AND si.CreatedAt = latest.MaxCreatedAt
            ORDER BY si.CreatedAt DESC;

            CREATE OR REPLACE VIEW LatestHardwareInventoriesView AS
            SELECT * FROM (
                SELECT *,
                       ROW_NUMBER() OVER (PARTITION BY MachineId ORDER BY CreatedAt DESC) AS rn
                FROM HardwareInventories
            ) ranked
            WHERE rn = 1
            ORDER BY CreatedAt DESC;

            CREATE OR REPLACE VIEW ComputerModelStatisticsView AS
            SELECT
                ComputerModel,
                COUNT(*) AS AnzahlMaschinen,
                COUNT(DISTINCT MachineId) AS EinzigartigeMaschinen,
                ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM LatestHardwareInventoriesView), 2) AS Prozentsatz,
                MIN(CreatedAt) AS ErsteErfassung,
                MAX(CreatedAt) AS LetzteErfassung
            FROM LatestHardwareInventoriesView
            WHERE ComputerModel IS NOT NULL
              AND ComputerModel != ''
            GROUP BY ComputerModel
            ORDER BY AnzahlMaschinen DESC;

            CREATE OR REPLACE VIEW ArchitectureStatisticsView AS
            SELECT
                Architecture,
                COUNT(*) AS AnzahlMaschinen,
                COUNT(DISTINCT MachineId) AS EinzigartigeMaschinen,
                ROUND(COUNT(*)::numeric * 100.0 / (SELECT COUNT(*) FROM LatestHardwareInventoriesView)::numeric, 2) AS Prozentsatz,
                AVG(ProcessorCores) AS DurchschnittlicheKerne,
                ROUND(AVG(TotalMemoryGB::numeric / 1024 / 1024 / 1024), 2) AS DurchschnittlicherSpeicherGB,
                MIN(CreatedAt) AS ErsteErfassung,
                MAX(CreatedAt) AS LetzteErfassung
            FROM LatestHardwareInventoriesView
            WHERE Architecture IS NOT NULL
              AND Architecture != ''
            GROUP BY Architecture
            ORDER BY AnzahlMaschinen DESC;

            CREATE OR REPLACE VIEW ModelArchitectureStatisticsView AS
            SELECT
                ComputerModel,
                Architecture,
                COUNT(*) AS AnzahlMaschinen,
                COUNT(DISTINCT MachineId) AS EinzigartigeMaschinen,
                ROUND(COUNT(*)::numeric * 100.0 / (SELECT COUNT(*) FROM LatestHardwareInventoriesView)::numeric, 2) AS Prozentsatz,
                ROUND(AVG(ProcessorCores::numeric), 0) AS DurchschnittlicheKerne,
                ROUND(AVG(TotalMemoryGB::numeric / 1024 / 1024 / 1024), 2) AS DurchschnittlicherSpeicherGB,
                MIN(CreatedAt) AS ErsteErfassung,
                MAX(CreatedAt) AS LetzteErfassung
            FROM LatestHardwareInventoriesView
            WHERE ComputerModel IS NOT NULL
              AND ComputerModel != ''
              AND Architecture IS NOT NULL
              AND Architecture != ''
            GROUP BY ComputerModel, Architecture
            ORDER BY AnzahlMaschinen DESC;

            CREATE OR REPLACE VIEW HardwareStatisticsOverview AS
            SELECT
                'ComputerModel' AS Kategorie,
                ComputerModel AS Wert,
                COUNT(*) AS Anzahl,
                ROUND(COUNT(*)::numeric * 100.0 / (SELECT COUNT(*) FROM LatestHardwareInventoriesView)::numeric, 2) AS Prozentsatz
            FROM LatestHardwareInventoriesView
            WHERE ComputerModel IS NOT NULL AND ComputerModel != ''
            GROUP BY ComputerModel

            UNION ALL

            SELECT
                'Architecture' AS Kategorie,
                Architecture AS Wert,
                COUNT(*) AS Anzahl,
                ROUND(COUNT(*)::numeric * 100.0 / (SELECT COUNT(*) FROM LatestHardwareInventoriesView)::numeric, 2) AS Prozentsatz
            FROM LatestHardwareInventoriesView
            WHERE Architecture IS NOT NULL AND Architecture != ''
            GROUP BY Architecture

            ORDER BY Kategorie, Anzahl DESC;

            CREATE OR REPLACE VIEW AllActiveMachinesView AS
            SELECT Id, Name, IPv4, IPv6, FQDN, Disabled, Deprovisioned, LastSeen, LastHarvested
            FROM Machines
            WHERE Disabled = FALSE AND Deprovisioned = FALSE;

            CREATE OR REPLACE VIEW AllActiveMachinesWithNetworkInfoView AS
            SELECT Id, Name, IPv4, IPv6, FQDN, Disabled, Deprovisioned, LastSeen, LastHarvested
            FROM Machines
            WHERE Disabled = FALSE AND Deprovisioned = FALSE AND (
                (IPv4 IS NOT NULL AND IPv4 != '') OR
                (IPv6 IS NOT NULL AND IPv6 != '') OR
                (FQDN IS NOT NULL AND FQDN != '')
            );

            CREATE OR REPLACE VIEW AllDisabledMachinesView AS
            SELECT Id, Name, IPv4, IPv6, FQDN, Disabled, Deprovisioned, LastSeen, LastHarvested
            FROM Machines
            WHERE Disabled = TRUE AND Deprovisioned = FALSE;

            CREATE OR REPLACE VIEW AllDeprovisionedMachinesView AS
            SELECT Id, Name, IPv4, IPv6, FQDN, Disabled, Deprovisioned, LastSeen, LastHarvested
            FROM Machines
            WHERE Disabled = TRUE AND Deprovisioned = TRUE;
            """;

        connection.Execute(createTablesAndViewsQuery);
    }

    /// <summary>
    /// DE: Speichert eine neue Maschine oder aktualisiert einen bestehenden Datensatz anhand des Namens.
    /// SQLite bleibt die fuehrende Datenbank; die explizite Id wird nach PostgreSQL uebernommen.
    /// EN: Saves a new machine or updates an existing row by name.
    /// SQLite remains the leading database; the explicit Id is adopted by PostgreSQL.
    /// </summary>
    /// <param name="machine">DE: Maschinenobjekt mit SQLite-Id. EN: Machine object with the SQLite Id.</param>
    /// <param name="isHarvester">DE: Steuert das erweiterte Harvester-Update. EN: Controls the extended harvester update.</param>
    /// <returns>
    /// DE: Die Id der gespeicherten Maschine.
    /// EN: The Id of the saved machine.
    /// </returns>
    /// <exception cref="ArgumentNullException">
    /// DE: Wird geworfen, wenn <paramref name="machine"/> <c>null</c> ist.
    /// EN: Thrown when <paramref name="machine"/> is <c>null</c>.
    /// </exception>
    /// <exception cref="ArgumentException">
    /// DE: Wird geworfen, wenn <paramref name="machine"/> keine gueltige Id enthaelt.
    /// EN: Thrown when <paramref name="machine"/> does not contain a valid Id.
    /// </exception>
    public async Task<int> SaveOrUpdateMachineAsync(Machine machine, bool isHarvester = false)
    {
        ArgumentNullException.ThrowIfNull(machine);

        if (machine.Id == 0)
        {
            throw new ArgumentException("Machine Id must be provided from SQLite before saving to PostgreSQL.", nameof(machine));
        }

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string selectQuery = "SELECT Id FROM Machines WHERE Name = @Name";
        var existingMachineId = await connection.QuerySingleOrDefaultAsync<int?>(selectQuery, new { machine.Name }).ConfigureAwait(false);
        var now = DateTime.UtcNow;

        if (existingMachineId.HasValue)
        {
            if (isHarvester)
            {
                const string updateHarvesterQuery =
                    """
                    UPDATE Machines
                    SET OperatingSystem = @OperatingSystem,
                        LastSeen = @LastSeen,
                        IPv4 = @IPv4,
                        IPv6 = @IPv6,
                        FQDN = @FQDN,
                        LastHarvested = @LastHarvested
                    WHERE Id = @Id
                    """;

                await connection.ExecuteAsync(
                    updateHarvesterQuery,
                    new
                    {
                        machine.OperatingSystem,
                        LastSeen = now,
                        machine.IPv4,
                        machine.IPv6,
                        machine.FQDN,
                        LastHarvested = now,
                        Id = existingMachineId.Value
                    }).ConfigureAwait(false);
            }
            else
            {
                const string updateQuery =
                    """
                    UPDATE Machines
                    SET OperatingSystem = @OperatingSystem,
                        LastSeen = @LastSeen
                    WHERE Id = @Id
                    """;

                await connection.ExecuteAsync(
                    updateQuery,
                    new
                    {
                        machine.OperatingSystem,
                        LastSeen = now,
                        Id = existingMachineId.Value
                    }).ConfigureAwait(false);
            }

            return existingMachineId.Value;
        }

        const string insertQuery =
            """
            INSERT INTO Machines (Id, Name, OperatingSystem, LastSeen, CreatedAt, IPv4, IPv6, FQDN, LastHarvested, Disabled, Deprovisioned)
            VALUES (@Id, @Name, @OperatingSystem, @LastSeen, @CreatedAt, @IPv4, @IPv6, @FQDN, @LastHarvested, @Disabled, @Deprovisioned)
            RETURNING Id
            """;

        return await connection.QuerySingleAsync<int>(
            insertQuery,
            new
            {
                machine.Id,
                machine.Name,
                machine.OperatingSystem,
                LastSeen = now,
                CreatedAt = now,
                machine.IPv4,
                machine.IPv6,
                machine.FQDN,
                LastHarvested = isHarvester ? now : (DateTime?)null,
                machine.Disabled,
                machine.Deprovisioned
            }).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Speichert eine Hardware-Momentaufnahme fuer die angegebene Maschine.
    /// EN: Saves a hardware snapshot for the specified machine.
    /// </summary>
    /// <param name="machineId">DE: Maschinen-Id. EN: Machine Id.</param>
    /// <param name="hardware">DE: Hardware-Inventar. EN: Hardware inventory.</param>
    public async Task SaveHardwareInventoryAsync(int machineId, HardwareInventory hardware)
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string insertQuery =
            """
            INSERT INTO HardwareInventories
            (MachineId, ComputerName, ComputerModel, ComputerManufacturer, Architecture, ProcessorName, ProcessorCores,
             TotalMemoryGB, AvailableMemoryGB, MemoryUsagePercent, CreatedAt)
            VALUES
            (@MachineId, @ComputerName, @ComputerModel, @ComputerManufacturer, @Architecture, @ProcessorName, @ProcessorCores,
             @TotalMemoryGB, @AvailableMemoryGB, @MemoryUsagePercent, @CreatedAt)
            """;

        await connection.ExecuteAsync(
            insertQuery,
            new
            {
                MachineId = machineId,
                ComputerName = hardware.System.MachineName,
                ComputerModel = hardware.System.Platform,
                ComputerManufacturer = hardware.System.UserName,
                hardware.System.Architecture,
                hardware.Cpu.ProcessorName,
                ProcessorCores = hardware.Cpu.ProcessorCount,
                TotalMemoryGB = hardware.Memory.TotalPhysicalMemory,
                AvailableMemoryGB = hardware.Memory.AvailablePhysicalMemory,
                MemoryUsagePercent = hardware.Memory.MemoryUsagePercentage,
                CreatedAt = DateTime.UtcNow
            }).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Serialisiert die Software-Teillisten nach JSON und speichert sie fuer die Maschine.
    /// EN: Serializes the software sub-collections to JSON and stores them for the machine.
    /// </summary>
    /// <param name="machineId">DE: Maschinen-Id. EN: Machine Id.</param>
    /// <param name="software">DE: Software-Inventar. EN: Software inventory.</param>
    public async Task SaveSoftwareInventoryAsync(int machineId, SoftwareInventory software)
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string insertQuery =
            """
            INSERT INTO SoftwareInventories
            (MachineId, ProcessesJson, InstalledSoftwareJson, ServicesJson, EnvironmentJson, StartupProgramsJson, RuntimeJson, CreatedAt)
            VALUES
            (@MachineId, @ProcessesJson, @InstalledSoftwareJson, @ServicesJson, @EnvironmentJson, @StartupProgramsJson, @RuntimeJson, @CreatedAt)
            """;

        await connection.ExecuteAsync(
            insertQuery,
            new
            {
                MachineId = machineId,
                ProcessesJson = JsonSerializer.Serialize(software.RunningProcesses),
                InstalledSoftwareJson = JsonSerializer.Serialize(software.InstalledSoftware),
                ServicesJson = JsonSerializer.Serialize(software.WindowsServices),
                EnvironmentJson = JsonSerializer.Serialize(software.EnvironmentVariables),
                StartupProgramsJson = JsonSerializer.Serialize(software.StartupPrograms),
                RuntimeJson = JsonSerializer.Serialize(software.Runtime),
                CreatedAt = DateTime.UtcNow
            }).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Gibt alle Maschinen sortiert nach Namen zurueck.
    /// EN: Returns all machines ordered by name.
    /// </summary>
    /// <returns>
    /// DE: Liste aller Maschinen.
    /// EN: List of all machines.
    /// </returns>
    public async Task<List<Machine>> GetMachinesAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT * FROM Machines ORDER BY Name";
        var machines = await connection.QueryAsync<Machine>(query).ConfigureAwait(false);
        return machines.ToList();
    }

    /// <summary>
    /// DE: Gibt alle aktiven Maschinen aus der View <c>AllActiveMachinesView</c> zurueck.
    /// EN: Returns all active machines from the <c>AllActiveMachinesView</c> view.
    /// </summary>
    /// <returns>
    /// DE: Liste aktiver Maschinen.
    /// EN: List of active machines.
    /// </returns>
    public async Task<List<MachineState>> GetAllActiveMachinesAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT * FROM AllActiveMachinesView ORDER BY Name";
        var machines = await connection.QueryAsync<MachineState>(query).ConfigureAwait(false);
        return machines.ToList();
    }

    /// <summary>
    /// DE: Gibt aktive Maschinen mit mindestens einem Netzwerkwert zurueck.
    /// EN: Returns active machines that have at least one network value.
    /// </summary>
    /// <returns>
    /// DE: Liste aktiver Maschinen mit Netzwerkinformationen.
    /// EN: List of active machines with network information.
    /// </returns>
    public async Task<List<MachineState>> GetAllActiveMachinesWithNetworkInfoAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT * FROM AllActiveMachinesWithNetworkInfoView ORDER BY Name";
        var machines = await connection.QueryAsync<MachineState>(query).ConfigureAwait(false);
        return machines.ToList();
    }

    /// <summary>
    /// DE: Gibt alle deaktivierten, aber nicht deprovisionierten Maschinen zurueck.
    /// EN: Returns all disabled but not deprovisioned machines.
    /// </summary>
    /// <returns>
    /// DE: Liste deaktivierter Maschinen.
    /// EN: List of disabled machines.
    /// </returns>
    public async Task<List<MachineState>> GetAllDisabledMachinesAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT * FROM AllDisabledMachinesView ORDER BY Name";
        var machines = await connection.QueryAsync<MachineState>(query).ConfigureAwait(false);
        return machines.ToList();
    }

    /// <summary>
    /// DE: Gibt alle deprovisionierten Maschinen zurueck.
    /// EN: Returns all deprovisioned machines.
    /// </summary>
    /// <returns>
    /// DE: Liste deprovisionierter Maschinen.
    /// EN: List of deprovisioned machines.
    /// </returns>
    public async Task<List<MachineState>> GetAllDeprovisionedMachinesAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT * FROM AllDeprovisionedMachinesView ORDER BY Name";
        var machines = await connection.QueryAsync<MachineState>(query).ConfigureAwait(false);
        return machines.ToList();
    }

    /// <summary>
    /// DE: Sucht eine Maschine ueber ihre Id.
    /// EN: Looks up a machine by its Id.
    /// </summary>
    /// <param name="id">DE: Maschinen-Id. EN: Machine Id.</param>
    /// <returns>
    /// DE: Die gefundene Maschine oder <c>null</c>.
    /// EN: The matching machine or <c>null</c>.
    /// </returns>
    public async Task<Machine?> GetMachineByIdAsync(int id)
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT * FROM Machines WHERE Id = @Id";
        return await connection.QuerySingleOrDefaultAsync<Machine>(query, new { Id = id }).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Sucht eine Maschine ueber ihren Namen.
    /// EN: Looks up a machine by its name.
    /// </summary>
    /// <param name="machineName">DE: Maschinenname. EN: Machine name.</param>
    /// <returns>
    /// DE: Die gefundene Maschine oder <c>null</c>.
    /// EN: The matching machine or <c>null</c>.
    /// </returns>
    public async Task<Machine?> GetMachineByNameAsync(string machineName)
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT * FROM Machines WHERE Name = @MachineName";
        return await connection.QuerySingleOrDefaultAsync<Machine>(query, new { MachineName = machineName }).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Liefert den neuesten Hardware-Eintrag einer Maschine.
    /// EN: Returns the most recent hardware record for a machine.
    /// </summary>
    /// <param name="machineId">DE: Maschinen-Id. EN: Machine Id.</param>
    /// <returns>
    /// DE: Neuester Hardware-Eintrag oder <c>null</c>.
    /// EN: Most recent hardware record or <c>null</c>.
    /// </returns>
    public async Task<HardwareInventories?> GetLatestHardwareInventoryAsync(int machineId)
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query =
            """
            SELECT * FROM HardwareInventories
            WHERE MachineId = @MachineId
            ORDER BY CreatedAt DESC
            LIMIT 1
            """;

        return await connection.QuerySingleOrDefaultAsync<HardwareInventories>(query, new { MachineId = machineId }).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Liefert den neuesten Software-Eintrag einer Maschine.
    /// EN: Returns the most recent software record for a machine.
    /// </summary>
    /// <param name="machineId">DE: Maschinen-Id. EN: Machine Id.</param>
    /// <returns>
    /// DE: Neuester Software-Eintrag oder <c>null</c>.
    /// EN: Most recent software record or <c>null</c>.
    /// </returns>
    public async Task<SoftwareInventories?> GetLatestSoftwareInventoryAsync(int machineId)
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query =
            """
            SELECT * FROM SoftwareInventories
            WHERE MachineId = @MachineId
            ORDER BY CreatedAt DESC
            LIMIT 1
            """;

        return await connection.QuerySingleOrDefaultAsync<SoftwareInventories>(query, new { MachineId = machineId }).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Berechnet den UTC-Cutoff fuer Aufraeumoperationen.
    /// EN: Calculates the UTC cutoff for cleanup operations.
    /// </summary>
    /// <param name="daysToKeep">DE: Anzahl Tage, die behalten werden sollen. EN: Number of days to keep.</param>
    /// <returns>
    /// DE: UTC-Zeitpunkt fuer die Loeschgrenze.
    /// EN: UTC timestamp used as the delete threshold.
    /// </returns>
    internal static DateTime CalculateCutoff(int daysToKeep) => DateTime.UtcNow.AddDays(-daysToKeep);

    /// <summary>
    /// DE: Loescht Hardware- und Software-Eintraege, die aelter als der berechnete Cutoff sind.
    /// EN: Deletes hardware and software rows that are older than the calculated cutoff.
    /// </summary>
    /// <param name="daysToKeep">DE: Aufbewahrungsdauer in Tagen. EN: Retention period in days.</param>
    public async Task CleanupOldRecordsAsync(int daysToKeep = 30)
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        var cutoffDate = CalculateCutoff(daysToKeep);

        const string deleteHardwareQuery = "DELETE FROM HardwareInventories WHERE CreatedAt < @CutoffDate";
        const string deleteSoftwareQuery = "DELETE FROM SoftwareInventories WHERE CreatedAt < @CutoffDate";

        await connection.ExecuteAsync(deleteHardwareQuery, new { CutoffDate = cutoffDate }).ConfigureAwait(false);
        await connection.ExecuteAsync(deleteSoftwareQuery, new { CutoffDate = cutoffDate }).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Prueft, ob mindestens eine Maschine vorhanden ist.
    /// EN: Checks whether at least one machine record exists.
    /// </summary>
    /// <returns>
    /// DE: <c>true</c>, wenn mindestens eine Maschine existiert.
    /// EN: <c>true</c> when at least one machine exists.
    /// </returns>
    public async Task<bool> HasMachineRecordsAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT EXISTS(SELECT 1 FROM Machines)";
        return await connection.QuerySingleAsync<bool>(query).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Prueft, ob mindestens ein Hardware-Inventareintrag vorhanden ist.
    /// EN: Checks whether at least one hardware inventory record exists.
    /// </summary>
    /// <returns>
    /// DE: <c>true</c>, wenn mindestens ein Hardware-Eintrag existiert.
    /// EN: <c>true</c> when at least one hardware record exists.
    /// </returns>
    public async Task<bool> HasHardwareInventoryRecordsAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT EXISTS(SELECT 1 FROM HardwareInventories)";
        return await connection.QuerySingleAsync<bool>(query).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Prueft, ob mindestens ein Software-Inventareintrag vorhanden ist.
    /// EN: Checks whether at least one software inventory record exists.
    /// </summary>
    /// <returns>
    /// DE: <c>true</c>, wenn mindestens ein Software-Eintrag existiert.
    /// EN: <c>true</c> when at least one software record exists.
    /// </returns>
    public async Task<bool> HasSoftwareInventoryRecordsAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT EXISTS(SELECT 1 FROM SoftwareInventories)";
        return await connection.QuerySingleAsync<bool>(query).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Gibt die Anzahl der Maschinen zurueck.
    /// EN: Returns the number of machines.
    /// </summary>
    /// <returns>
    /// DE: Gesamtanzahl der Maschinen.
    /// EN: Total number of machines.
    /// </returns>
    public async Task<int> GetMachineCountAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT COUNT(*) FROM Machines";
        return await connection.QuerySingleAsync<int>(query).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Gibt die Anzahl der Hardware-Inventareintraege zurueck.
    /// EN: Returns the number of hardware inventory rows.
    /// </summary>
    /// <returns>
    /// DE: Gesamtanzahl der Hardware-Eintraege.
    /// EN: Total number of hardware rows.
    /// </returns>
    public async Task<int> GetHardwareInventoryCountAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT COUNT(*) FROM HardwareInventories";
        return await connection.QuerySingleAsync<int>(query).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Gibt die Anzahl der Software-Inventareintraege zurueck.
    /// EN: Returns the number of software inventory rows.
    /// </summary>
    /// <returns>
    /// DE: Gesamtanzahl der Software-Eintraege.
    /// EN: Total number of software rows.
    /// </returns>
    public async Task<int> GetSoftwareInventoryCountAsync()
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        const string query = "SELECT COUNT(*) FROM SoftwareInventories";
        return await connection.QuerySingleAsync<int>(query).ConfigureAwait(false);
    }

    /// <summary>
    /// DE: Importiert Maschinen aus einer CSV-Datei innerhalb einer PostgreSQL-Transaktion.
    /// Vorhandene Maschinen werden uebersprungen; bei Fehlern wird vollstaendig zurueckgerollt.
    /// EN: Imports machines from a CSV file inside a PostgreSQL transaction.
    /// Existing machines are skipped; failures trigger a full rollback.
    /// </summary>
    /// <param name="csvFilePath">DE: Pfad zur CSV-Datei. EN: Path to the CSV file.</param>
    /// <returns>
    /// DE: Anzahl neu importierter Maschinen.
    /// EN: Number of newly imported machines.
    /// </returns>
    /// <exception cref="FileNotFoundException">
    /// DE: Wird geworfen, wenn die CSV-Datei nicht existiert.
    /// EN: Thrown when the CSV file does not exist.
    /// </exception>
    /// <exception cref="Exception">
    /// DE: Wird geworfen, wenn der Import fehlschlaegt und ein Rollback ausgeloest wurde.
    /// EN: Thrown when the import fails and a rollback was triggered.
    /// </exception>
    public async Task<int> InitializeMachinesFromCsvAsync(string csvFilePath)
    {
        if (File.Exists(csvFilePath) is false)
        {
            throw new FileNotFoundException($"The specified CSV file does not exist {csvFilePath}.");
        }

        var importedCount = 0;
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync().ConfigureAwait(false);

        await using var transaction = await connection.BeginTransactionAsync().ConfigureAwait(false);

        try
        {
            using var reader = new StreamReader(csvFilePath);
            using var csv = new CsvReader(reader, CultureInfo.InvariantCulture);

            csv.Context.RegisterClassMap<MachineMapFromCsv>();

            var machines = csv.GetRecords<MachineFromCsv>().ToList();

            foreach (var machine in machines)
            {
                if (string.IsNullOrWhiteSpace(machine.Name))
                {
                    throw new InvalidOperationException("Machine name must not be empty during CSV import.");
                }

                const string selectQuery = "SELECT Id FROM Machines WHERE Name = @Name";
                var existingMachineId = await connection.QuerySingleOrDefaultAsync<int?>(
                    selectQuery,
                    new { machine.Name },
                    transaction).ConfigureAwait(false);

                if (existingMachineId.HasValue)
                {
                    continue;
                }

                const string insertQuery =
                    """
                    INSERT INTO Machines (Name, OperatingSystem, LastSeen, CreatedAt, IPv4, IPv6, FQDN, Disabled, Deprovisioned)
                    VALUES (@Name, @OperatingSystem, @LastSeen, @CreatedAt, @IPv4, @IPv6, @FQDN, @Disabled, @Deprovisioned)
                    """;

                await connection.ExecuteAsync(
                    insertQuery,
                    new
                    {
                        machine.Name,
                        machine.OperatingSystem,
                        LastSeen = machine.LastSeen ?? DateTime.UtcNow,
                        CreatedAt = DateTime.UtcNow,
                        machine.IPv4,
                        machine.IPv6,
                        machine.FQDN,
                        machine.Disabled,
                        machine.Deprovisioned
                    },
                    transaction).ConfigureAwait(false);

                importedCount++;
            }

            await transaction.CommitAsync().ConfigureAwait(false);
            return importedCount;
        }
        catch (Exception ex)
        {
            await transaction.RollbackAsync().ConfigureAwait(false);
            throw new Exception("Import fehlgeschlagen — Transaktion zurückgerollt.", ex);
        }
    }

    private void EnsureDatabaseExists(string targetDatabase)
    {
        var adminCsBuilder = new NpgsqlConnectionStringBuilder(_connectionString)
        {
            Database = "postgres"
        };

        using var adminConnection = new NpgsqlConnection(adminCsBuilder.ConnectionString);
        adminConnection.Open();

        using var checkDbExistsCmd = new NpgsqlCommand("SELECT 1 FROM pg_database WHERE datname = @dbname", adminConnection);
        checkDbExistsCmd.Parameters.AddWithValue("dbname", targetDatabase);
        var dbExists = checkDbExistsCmd.ExecuteScalar() is not null;

        if (dbExists is false)
        {
            var quotedDbName = QuoteIdentifier(targetDatabase);
            using var createCmd = new NpgsqlCommand($"CREATE DATABASE {quotedDbName}", adminConnection);
            createCmd.ExecuteNonQuery();
        }
    }

    private string GetTargetDatabaseName()
    {
        var csStringBuilder = new NpgsqlConnectionStringBuilder(_connectionString);
        var dbName = csStringBuilder.Database;

        if (string.IsNullOrWhiteSpace(dbName))
        {
            throw new InvalidOperationException("No target database specified in the PostgreSQL connection string.");
        }

        return dbName;
    }

    private static string QuoteIdentifier(string identifier)
    {
        return "\"" + identifier.Replace("\"", "\"\"") + "\"";
    }
}
