using Dapper;
using Npgsql;

namespace InventarWorkerCommon.Services.Database;

/// <summary>
/// Provides services for interacting with a PostgreSQL database.
/// This class facilitates connection management and initialization
/// of the database using the Npgsql ADO.NET library.
/// </summary>
public class PgSqlDbService
{
    private readonly string _connectionString;

    /// <summary>
    /// Provides services for interacting with a PostgreSQL database.
    /// This class simplifies managing the PostgreSQL database connection
    /// and enables database initialization.
    /// </summary>
    public PgSqlDbService(string connectionString)
    {
        _connectionString = connectionString;
    }

    /// <summary>
    /// Initializes the PostgreSQL database by opening a connection
    /// using the provided connection string. This method ensures
    /// that the database is ready for operations.
    /// </summary>
    public void InitializeDatabase()
    {
#if DEBUG
        // Determine the target database name from the connection string
        var targetDatabase = GetTargetDatabaseName();
        // Ensure the target database exists, create it if necessary
        EnsureDatabaseExists(targetDatabase);
#else
        EnsureDatabaseExists(GetTargetDatabaseName());
#endif

        // Finally, try opening a connection to the target DB to ensure it's ready
        using var connection = new NpgsqlConnection(_connectionString);
        connection.Open();

        var createTablesAndViewsQuery =
            """
            -- Ensure the Machines table is created with appropriate fields
            
            CREATE TABLE IF NOT EXISTS Machines (
                Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                Name TEXT NOT NULL UNIQUE,
                OperatingSystem TEXT,
                LastSeen timestamptz,
                CreatedAt timestamptz DEFAULT now(),
                IPv4 TEXT,
                IPv6 TEXT,
                FQDN TEXT,
                Disabled INTEGER NOT NULL DEFAULT 0,
                Deprovisioned INTEGER NOT NULL DEFAULT 0,
                LastHarvested timestamptz
            );
            
            -- Ensure the HardwareInventories table is created with appropriate fields
            
            CREATE TABLE IF NOT EXISTS HardwareInventories (
               Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               MachineId INTEGER NOT NULL,
               ComputerName TEXT,
               ComputerModel TEXT,
               ComputerManufacturer TEXT,
               Architecture TEXT,
               ProcessorName TEXT,
               ProcessorCores INTEGER,
               TotalMemoryGB REAL,
               AvailableMemoryGB REAL,
               MemoryUsagePercent REAL,
               CreatedAt timestamptz DEFAULT now(),
               FOREIGN KEY (MachineId) REFERENCES Machines(Id)
            );
            -- Ensure the SoftwareInventories table is created with appropriate fields
            
            CREATE TABLE IF NOT EXISTS SoftwareInventories (
               Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               MachineId INTEGER NOT NULL,
               ProcessesJson TEXT,
               InstalledSoftwareJson TEXT,
               ServicesJson TEXT,
               EnvironmentJson TEXT,
               StartupProgramsJson TEXT,
               RuntimeJson TEXT,
               CreatedAt timestamptz DEFAULT now(),
               FOREIGN KEY (MachineId) REFERENCES Machines(Id)
            );
            
            -- Create indexes to improve query performance
            CREATE INDEX IF NOT EXISTS idx_machines_name ON Machines(Name);
            CREATE INDEX IF NOT EXISTS idx_hardware_machine_created ON HardwareInventories(MachineId, CreatedAt);
            CREATE INDEX IF NOT EXISTS idx_software_machine_created ON SoftwareInventories(MachineId, CreatedAt);
            
            -- This SQL script creates a view named `hardwareinventory` that aggregates hardware information
            -- from the `Machines` and `HardwareInventories` tables.
            -- It includes machine ID, name, architecture, processor cores, total memory,
            -- available memory, and memory usage percentage.
            
            CREATE OR REPLACE VIEW hardware_inventory_view AS
            SELECT DISTINCT ON (m.id)
                m.id   AS machine_id,
                m.name AS machine_name,
                h.architecture,
                h.processorcores,
                round(h.totalmemorygb::numeric / 1024 / 1024 / 1024, 2)      AS totalmemorygb,
                round(h.availablememorygb::numeric / 1024 / 1024 / 1024, 2)  AS availablememorygb,
                round(h.memoryusagepercent::numeric, 2)                      AS memoryusagepercent
            FROM machines m
                     JOIN hardwareinventories h ON h.machineid = m.id
            ORDER BY m.id, m.name ASC;
            
            -- This SQL script retrieves the latest software and hardware inventory records for each machine.
            -- It uses a common table expression (CTE) to find the latest records based on the CreatedAt timestamp.
            -- The script also creates a view for the latest software inventories.
            
            CREATE OR REPLACE VIEW LatestSoftwareInventoriesView AS
            SELECT si.*
            FROM SoftwareInventories si
                     INNER JOIN (
                SELECT MachineId, MAX(CreatedAt) as MaxCreatedAt
                FROM SoftwareInventories
                GROUP BY MachineId
            ) latest ON si.MachineId = latest.MachineId AND si.CreatedAt = latest.MaxCreatedAt
            ORDER BY si.CreatedAt DESC;
            
            -- This SQL script retrieves the latest hardware inventory records for each machine.
            -- It uses a common table expression (CTE) to find the latest records based on the CreatedAt timestamp.
            -- It also creates a view for the latest hardware inventories.
            
            CREATE OR REPLACE VIEW LatestHardwareInventoriesView AS
            SELECT * FROM (
                              SELECT *,
                                     ROW_NUMBER() OVER (PARTITION BY MachineId ORDER BY CreatedAt DESC) as rn
                              FROM HardwareInventories
                          ) ranked
            WHERE rn = 1
            ORDER BY CreatedAt DESC;
            
            -- Statistics view for ComputerModel distribution
            -- This SQL script creates a view that aggregates statistics for each ComputerModel
            -- including the count of machines, unique machines, percentage of total machines,
            -- and the first and last recorded timestamps.
            
            CREATE OR REPLACE VIEW ComputerModelStatisticsView AS
            SELECT
                ComputerModel,
                COUNT(*) as AnzahlMaschinen,
                COUNT(DISTINCT MachineId) as EinzigartigeMaschinen,
                ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM LatestHardwareInventoriesView), 2) as Prozentsatz,
                MIN(CreatedAt) as ErsteErfassung,
                MAX(CreatedAt) as LetzteErfassung
            FROM LatestHardwareInventoriesView
            WHERE ComputerModel IS NOT NULL
              AND ComputerModel != ''
            GROUP BY ComputerModel
            ORDER BY AnzahlMaschinen DESC;
            
            -- Statistics view for architecture distribution
            -- This SQL script creates a view that aggregates statistics for each architecture
            -- including the count of machines, unique machines, percentage of total machines,
            
            CREATE OR REPLACE VIEW ArchitectureStatisticsView AS
            SELECT
                Architecture,
                COUNT(*) as AnzahlMaschinen,
                COUNT(DISTINCT MachineId) as EinzigartigeMaschinen,
                ROUND(COUNT(*)::numeric * 100.0 / (SELECT COUNT(*) FROM LatestHardwareInventoriesView)::numeric, 2) as Prozentsatz,
                AVG(ProcessorCores) as DurchschnittlicheKerne,
                ROUND(AVG(TotalMemoryGB::numeric / 1024 /1024 /1024),2) as DurchschnittlicherSpeicherGB,
                MIN(CreatedAt) as ErsteErfassung,
                MAX(CreatedAt) as LetzteErfassung
            FROM LatestHardwareInventoriesView
            WHERE Architecture IS NOT NULL
              AND Architecture != ''
            GROUP BY Architecture
            ORDER BY AnzahlMaschinen DESC;
            
            -- Combined statistics view for ComputerModel and Architecture
            -- This SQL script creates a view that aggregates statistics for each combination
            -- of ComputerModel and Architecture,
            -- including the count of machines, unique machines, percentage of total machines,
            -- average processor cores, average total memory in GB, and the first and last recorded timestamps.
            
            CREATE OR REPLACE VIEW ModelArchitectureStatisticsView AS
            SELECT
                ComputerModel,
                Architecture,
                COUNT(*) as AnzahlMaschinen,
                COUNT(DISTINCT MachineId) as EinzigartigeMaschinen,
                ROUND(COUNT(*)::numeric * 100.0 / (SELECT COUNT(*) FROM LatestHardwareInventoriesView)::numeric, 2) as Prozentsatz,
                ROUND(AVG(ProcessorCores::numeric), 0) as DurchschnittlicheKerne,
                ROUND(AVG(TotalMemoryGB::numeric / 1024 / 1024 / 1024),2) as DurchschnittlicherSpeicherGB,
                MIN(CreatedAt) as ErsteErfassung,
                MAX(CreatedAt) as LetzteErfassung
            FROM LatestHardwareInventoriesView
            WHERE ComputerModel IS NOT NULL
              AND ComputerModel != ''
              AND Architecture IS NOT NULL
              AND Architecture != ''
            GROUP BY ComputerModel, Architecture
            ORDER BY AnzahlMaschinen DESC;
            
            -- Advanced Hardware Statistics View
            -- This SQL script creates a view that provides an overview of hardware statistics
            -- including the count of machines, unique machines, percentage of total machines,
            -- and the first and last recorded timestamps for ComputerModel and Architecture.
            
            CREATE OR REPLACE VIEW HardwareStatisticsOverview AS
            SELECT
                'ComputerModel' as Kategorie,
                ComputerModel as Wert,
                COUNT(*) as Anzahl,
                ROUND(COUNT(*)::numeric * 100.0 / (SELECT COUNT(*) FROM LatestHardwareInventoriesView)::numeric, 2) as Prozentsatz
            FROM LatestHardwareInventoriesView
            WHERE ComputerModel IS NOT NULL AND ComputerModel != ''
            GROUP BY ComputerModel
            
            UNION ALL
            
            SELECT
                'Architecture' as Kategorie,
                Architecture as Wert,
                COUNT(*) as Anzahl,
                ROUND(COUNT(*)::numeric * 100.0 / (SELECT COUNT(*) FROM LatestHardwareInventoriesView)::numeric, 2) as Prozentsatz
            FROM LatestHardwareInventoriesView
            WHERE Architecture IS NOT NULL AND Architecture != ''
            GROUP BY Architecture
            
            ORDER BY Kategorie, Anzahl DESC;
            
            -- View to retrieve all active achines (not disabled or deprovisioned)
            -- This view selects all machines that are currently active, meaning they are not disabled or deprovisioned.
            -- It includes the Id, Name, IPv4, IPv6, FQDN, Disabled, Deprovisioned, LastSeen, and LastHarvested columns.
            -- The view can be used to quickly access the list of active machines without having to filter the Machines table each time.
            -- The view is created only if it does not already exist.
            -- This allows for efficient querying of active machines in the inventory system.
            -- The view can be used to monitor the status of machines and ensure that only active machines are considered in reports and analyses.
            -- The view can be queried like a regular table, making it easy to integrate into existing queries and reports.
            -- The view is particularly useful for inventory management, monitoring.
            
            CREATE OR REPLACE VIEW AllActiveMachinesView AS
            SELECT Id, Name, IPv4, IPv6, FQDN, Disabled, Deprovisioned, LastSeen, LastHarvested
            FROM Machines
            WHERE DISABLED = 0 AND DEPROVISIONED = 0;
            
            -- View to retrieve all active machines with network information (not disabled or deprovisioned)
            -- This view selects all machines that are currently active, meaning they are not disabled or deprovisioned.
            -- It includes the Id, Name, IPv4, IPv6, FQDN, Disabled, Deprovisioned, LastSeen, and LastHarvested columns.
            -- The view can be used to quickly access the list of active machines without having to filter the Machines table each time.
            -- The view is created only if it does not already exist.
            -- This allows for efficient querying of active machines in the inventory system.
            -- The view can be used to monitor the status of machines and ensure that only active machines are considered in reports and analyses.
            -- The view can be queried like a regular table, making it easy to integrate into existing queries and reports.
            -- The view is particularly useful for inventory management, monitoring.
            
            CREATE OR REPLACE VIEW AllActiveMachinesWithNetworkInfoView AS
            SELECT Id, Name, IPv4, IPv6, FQDN, Disabled, Deprovisioned, LastSeen, LastHarvested
            FROM Machines
            WHERE DISABLED = 0 AND DEPROVISIONED = 0 AND (
                (IPv4 IS NOT NULL AND IPv4 != '') OR
                (IPv6 IS NOT NULL AND IPv6 != '') OR
                (FQDN IS NOT NULL AND FQDN != '')
                );
            
            -- View to retrieve all disabled machines (not deprovisioned)
            -- This view selects all machines that are currently disabled, meaning they are not deprovisioned.
            -- It includes the Id, Name, IPv4, IPv6, FQDN, Disabled, Deprovisioned, LastSeen, and LastHarvested columns.
            -- The view can be used to quickly access the list of disabled machines without having to filter the Machines table each time.
            -- The view is created only if it does not already exist.
            -- This allows for efficient querying of disabled machines in the inventory system.
            -- The view can be used to monitor the status of machines and ensure that only disabled machines are considered in reports and analyses.
            -- The view can be queried like a regular table, making it easy to integrate into existing queries and reports.
            -- The view is particularly useful for inventory management, monitoring.
            
            CREATE OR REPLACE VIEW AllDisabledMachinesView AS
            SELECT Id, Name, IPv4, IPv6, FQDN, Disabled, Deprovisioned, LastSeen, LastHarvested
            FROM Machines
            WHERE DISABLED = 1 AND DEPROVISIONED = 0;
            
            -- View to retrieve all deprovisioned machines (disabled)
            -- This view selects all machines that are currently deprovisioned, meaning they are disabled and marked as deprovisioned.
            -- It includes the Id, Name, IPv4, IPv6, FQDN, Disabled, Deprovisioned, LastSeen, and LastHarvested columns.
            -- The view can be used to quickly access the list of deprovisioned machines without having to filter the Machines table each time.
            -- The view is created only if it does not already exist.
            -- This allows for efficient querying of deprovisioned machines in the inventory system.
            -- The view can be used to monitor the status of machines and ensure that only deprovisioned machines are considered in reports and analyses.
            -- The view can be queried like a regular table, making it easy to integrate into existing queries and reports.
            -- The view is particularly useful for inventory management, monitoring, and auditing purposes.
            -- It helps in identifying machines that have been deprovisioned.
            
            CREATE OR REPLACE VIEW AllDeprovisionedMachinesView AS
            SELECT Id, Name, IPv4, IPv6, FQDN, Disabled, Deprovisioned, LastSeen, LastHarvested
            FROM Machines
            WHERE DISABLED = 1 AND DEPROVISIONED = 1;
            """;

        connection.Execute(createTablesAndViewsQuery);
    }

    /// <summary>
    /// Ensures that the specified PostgreSQL database exists on the server.
    /// Connects to the maintenance database and creates the target database if it doesn't exist.
    /// </summary>
    /// <param name="targetDatabase">The name of the database that should exist.</param>
    private void EnsureDatabaseExists(string targetDatabase)
    {
        // Build an admin connection string to the maintenance database (postgres)
        var adminCsBuilder = new NpgsqlConnectionStringBuilder(_connectionString)
        {
            Database = "postgres"
        };

        // Connect to maintenance DB and ensure target DB exists
        using var adminConnection = new NpgsqlConnection(adminCsBuilder.ConnectionString);
        adminConnection.Open();

        // Check if database exists
        using var checkDbExistsCmd = new NpgsqlCommand("SELECT 1 FROM pg_database WHERE datname = @dbname", adminConnection);
        checkDbExistsCmd.Parameters.AddWithValue("dbname", targetDatabase);
        var dbExists = checkDbExistsCmd.ExecuteScalar() is not null;

        if (dbExists is false)
        {
            // Create database with a quoted identifier to handle special characters/casing
            var quotedDbName = QuoteIdentifier(targetDatabase);
            using var createCmd = new NpgsqlCommand($"CREATE DATABASE {quotedDbName}", adminConnection);
            createCmd.ExecuteNonQuery();
        }
    }

    /// <summary>
    /// Extracts and validates the target database name from the configured connection string.
    /// </summary>
    /// <returns>The database name specified in the connection string.</returns>
    /// <exception cref="InvalidOperationException">Thrown if no database is specified in the connection string.</exception>
    private string GetTargetDatabaseName()
    {
        var csStringBuilder = new NpgsqlConnectionStringBuilder(_connectionString);
        var dbName = csStringBuilder.Database;

        if (string.IsNullOrWhiteSpace(dbName))
        {
            throw new InvalidOperationException("No target database specified in the PostgreSQL connection string.");
        }

        return dbName;
    }

    /// <summary>
    /// Quotes the provided identifier to ensure it is valid and safe for use
    /// in PostgreSQL database operations. The method adds double quotes around
    /// the identifier and escapes any existing quotes within it, adhering
    /// to PostgreSQL rules for quoted identifiers.
    /// </summary>
    /// <param name="identifier">The identifier to be quoted, which may contain special characters or reserved words.</param>
    /// <returns>A quoted string compliant with PostgreSQL identifier rules.</returns>
    private static string QuoteIdentifier(string identifier)
    {
        // Quote with double quotes and escape existing quotes per PostgreSQL rules
        return "\"" + identifier.Replace("\"", "\"\"") + "\"";
    }


}