### GET request to example server
GET http://localhost:5000/api/inventar/machines

###

### GET request to example server
GET http://localhost:5000/api/inventar/hardware-overview

###

### GET request to example server
GET http://localhost:5000/api/inventar/machines/LAPTOP-64643G0F/hardware

###

### GET request to example server
GET http://localhost:5000/api/inventar/machines/LAPTOP-64643G0F/software

###

### GET request to example server
GET http://localhost:5000/swagger/index.html
Accept: application/json

###
